version: '3.8'
services:
  db:
    image: postgres:15
    container_name: productapi-db
    environment:
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpass
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - productapi-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productapi-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=productapi-db;Port=5432;Database=productdb;Username=productuser;Password=productpass"
    ports:
      - "5290:5290"
    depends_on:
      - db
    networks:
      - productapi-net

volumes:
  db_data:

networks:
  productapi-net:
    driver: bridge
